### ISSUE TITLE
using streamedAnswer.ask is not setting stream=true in request

### ISSUE THREAD

**Issue by prateekshac1** [SwiftedMind/GPTSwift#7]
I'm using chat/completions with gpt-4, and am trying to use the streaming mode. But I see that in the request sent, stream parameter is set to false. Is there anything else I should be doing to stream, other than using streamedAnswer.ask ?

This is my request function:
```
private func makeRequest(with text:String) async throws -> String? {
        let request = ChatRequest.gpt4 { request in
            request.messages = [
                .init(role: .user, content: text)
            ]
            request.temperature = Double(K.OpenAI.temperature)
            request.maximumTokens = K.OpenAI.maxTokens
        }
        print("Making ChatGPT request: \(request)")
        do {
            var response = ""
            for try await nextWord in try await chatGPT.streamedAnswer.ask(request: request) {
                print("\(nextWord)")
                response += nextWord
            }
            return response

        } catch {
            print("Error running chatgpt request: \(error.localizedDescription)")
            return nil
        }
    }
```

**Comment by SwiftedMind** [comment]
Hey @prateekshac1,

Your code should be correct, this is actually a bug in the framework. I must have accidentally deleted something while refactoring. Sorry about that!

I've released a hotfix that should resolve your issue. Let me know if there are any other problems.
https://github.com/SwiftedMind/GPTSwift/releases/tag/3.0.1

**Comment by prateekshac1** [comment]
Yes, it's working now. Thank you for the quick fix :). And for the wrapper. Super useful!

**Comment by SwiftedMind** [comment]
Awesome! Glad it's working for you :)
